import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { Footer, Header } from "../layout";
import { ClerkProvider } from "@clerk/nextjs";

const pop = Montserrat({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="no-visible-scrollbar scroll-smooth" lang="en">
      <ClerkProvider>
        <body className={`${pop.className}  text-body`}>
          <Header />
          {children}
          <Footer />
        </body>
      </ClerkProvider>
    </html>
  );
}
